#The configuration file for application devices
#
# Description of parameters
# The configuration of a device starts with "---" separator, and is a simple
# set of parameters in the following form
#
# parameter: value
#  
# There are two main configuration parameters, which are enough to configure a device:
# 
# ---
# alias: "device_alias"
# name:  "device_name"

# where "alias" is an internal readonly property defined in the implementation of a device
# and "name" is a device name which is used in the application and visible to a user.
#
# The "active" property is used to include or exclude a device from the application.
#
# The "group" property is used to set a group name which a device belongs to,
# if not given, it is an empty string.
#
# For more information, see the manual.
#

# dummy slit1
---
alias: dummy_slit1_left
name: slit1_left
active: True
group: "Aperture/Slit1"

# dummy slit1
---
alias: dummy_slit1_right
name: slit1_right
active: True
group: "Aperture/Slit1"


# dummy slit1
---
alias: dummy_slit1_top
name: slit1_top
active: True
group: "Aperture/Slit1"

# dummy slit1
---
alias: dummy_slit1_bottom
name: slit1_bottom
active: True
group: "Aperture/Slit1"


# dummy slit2
---
alias: dummy_slit2_left
name: slit2_left
active: True
group: "Aperture/Slit2"

# dummy slit2
---
alias: dummy_slit2_right
name: slit2_right
active: True
group: "Aperture/Slit2"


# dummy slit2
---
alias: dummy_slit2_top
name: slit2_top
active: True
group: "Aperture/Slit2"

# dummy slit2
---
alias: dummy_slit2_bottom
name: slit2_bottom
active: True
group: "Aperture/Slit2"

# dummy shutter
---
alias: dummy_shutter
name: shutter
active: True
group: "Dummy"


# dummy fpga
---
alias: dummy_fpga
name: fpga
active: True
group: "Controllers"
units: "counts"

# dummy detector
---
alias: dummy_detector
name: detector
active: True
group: "Controllers"
units: "counts"

# dummy psd
---
alias: dummy_psd
name: psd
active: True
group: "PSD"
units: "counts"

# fpga time
---
alias: fpga_time
name: time
active: True
group: "Monitors"
units: "sec"

# fpga monitor
---
alias: fpga_monitor1
name: monitor1
active: True
group: "Monitors"
units: "counts"

# fpga monitor
---
alias: fpga_monitor2
name: monitor2
active: True
group: "Monitors"
units: "counts"
